version: "3"
services:
  mqtt:
    image: iqtlabs/edgetech-mqtt:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped
  daisy:
    image: iqtlabs/edgetech-daisy:latest
    network_mode: "host"
    devices:
      - "/dev/ttyACM0:/dev/serial0"
    environment:
      - MQTT_IP=127.0.0.1
    build:
      context: ./daisy
      dockerfile: ./Dockerfile
    restart: unless-stopped
    depends_on: 
      - mqtt