version: "3"
services:
  daisy:
    image: iqtlabs/edgetech-daisy:latest
    devices:
      - "/dev/ttyACM0:/dev/serial0"
    build:
      context: ./daisy
      dockerfile: ./Dockerfile
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
    env_file:
      - daisy-wo-mqtt.env
